config/routes.rb
Rails.application.routes.draw do
 root to: 'toppages#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: "sessions#create"

 delete 'logout', to: 'sessions#destroy'

 get 'signup', to:'users#new'
 
 resources :users, only: [:index, :show, :new, :create, :edit, :update] do
  member do
   get :followings
   get :followers
   get :likes
  end
 end
 
 resources :posts, only: [:new, :show, :create, :destroy] do
   resources :comments, only: [:create]
 end
 
 resources :comments, only: [:destroy]
  
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      flash[:success] = 'コメントを送信しました'
      redirect_back(fallback_location: root_url)
    else
      flash[:danger] = 'コメントを送信できませんでした'
      redirect_back(fallback_location: root_url)
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'コメントを削除しました'
    redirect_back(fallback_location: root_url)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    unless @comment
      redirect_to root_url
    end
  end
end

app/views/comments/_comments.html.erb
<% if comments.any? %>
  <% comments.each do |comment| %>
    <div class="card m-3">
      <div class="card-top m-3">
        <%= image_tag comment.user.profile_image.to_s, size: "50x50" %>
        <% if current_user == comment.user %>
          <%= comment.user.name %>
        <% else %>
          <%= link_to comment.user.name, user_path(comment.user) %>
        <% end %>
      </div>
  
      <div class="m-3">
        <%= comment.content %>
      </div>
      <div class="m-3">
        <% if current_user == comment.user %>
        <%= link_to "Delete", comment, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="card mb-5">
  <div class="card-top mt-3 ml-3">
  <%= image_tag current_user.profile_image.to_s, size: "50x50" %>
  <%= current_user.name %>
  </div>

  <%= form_with(model: @comment, scope: :comment, url: post_comments_path(@post), local: true) do |f| %>
  <div class="m-3">
    <%= f.label :comment, "Comment" %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <%= f.submit "Send", class: 'btn btn-primary m-3' %>
</div>
<% end %>