config/routes.rb
Rails.application.routes.draw do
 root to: 'toppages#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: "sessions#create"

 delete 'logout', to: 'sessions#destroy'

 get 'signup', to:'users#new'
 
 resources :users, only: [:index, :show, :new, :create, :edit, :update] do
  member do
   get :followings
   get :followers
   get :likes
  end
 end
 
 resources :posts, only: [:new, :show, :create, :destroy] do
   resources :comments, only: [:create]
 end
 
 resources :comments, only: [:destroy]
  
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  mount_uploader :profile_image, ProfileImageUploader
  validates :name, presence: true, length: {maximum: 50 }
  validates :email, presence: true, length: {maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :favorites
  has_many :favposts, through: :favorites, source: :post
  has_many :comments
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids + [self.id])
  end
  
  def like(post)
    favorites.find_or_create_by(post_id: post.id)
  end
  
  def unlike(post)
    favorite = favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  def favpost?(post)
    self.favposts.include?(post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :following, :followers, :likes]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(27)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_url
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'プロフィールを更新しました'
      redirect_to @user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @favposts = @user.favposts.page(params[:page])
    counts(@user)
  end
  
  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :email, :password, :password_confirmation)
  end
  
end

app/views/users/_users.html.erb
<% if users.any? %>

<div class="row">
  <% users.each do |user| %>
  <div class="card">
    <div class="card-top mt-3 ml-3">
      <%= user.name %>
    </div>
    <div class="card-body">
      <% if user.profile_image? %>
        <%= image_tag user.profile_image.to_s, size: "200x200" %>
      <% else %>
        <%= image_tag "default_img.jpg", size: "200x200" %>
      <% end %>
    </div>
    <div class="card-text mb-3 ml-3">
      <%= link_to "profile", user_path(user) %>
    </div>
  </div>
<% end %>
</div>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<h3>Update your profile</h3>

    <%= form_with(model: @user, local:true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.label :profile_image, 'Profile Image' %>
      <br>
      <%= image_tag @user.profile_image.url(:thumb) if @user.profile_image? %>
      <%= f.file_field :profile_image  %>
    </div>
    
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  <%= f.submit 'Save', class: "btn btn-primary" %>
  
<% end %>

app/views/users/followers.html.erb
<div class="row">
  <% if @user.profile_image? %>
    <%= image_tag @user.profile_image.to_s, size: "100x100" %>
  <% else %>
    <%= image_tag "default_img.jpg", size: "100x100" %>
  <% end %>
  
  <div class="col-sm-8">
    <div class="m-3">
    <h3><%= @user.name %></h3>
    <% if @user == current_user %>
      <%= link_to 'edit profile', edit_user_path, class: 'btn btn-outline-primary btn-sm' %>
    <% else %>
      <h3><%= render 'relationships/follow_button', user: @user %></h3>
    <% end %>
    </div>
    <ul class="nav nav-pills">
      
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followings_user_path(@user)) %>">Following  
        <span class="badge badge-secondary"><%= @count_followings %></span></a>
      </li>
      
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower  
        <span class="badge badge-secondary"><%= @count_followers %></span></a>
      </li>
    </ul>

    <div>
      <ul class="nav nav-tabs nav-justified mb-3">
        
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(user_path(@user)) %>">Post 
          <span class="badge badge-secondary"><%= @count_posts %></span></a>
        </li>
      
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes 
          <span class="badge badge-secondary"><%= @count_favposts %></span></a>
        </li>
      </ul>
    
    </div>
    <%= render 'users', users: @followers %>
  </div>
  
</div>

app/views/users/followings.html.erb
<div class="row">
  <% if @user.profile_image? %>
    <%= image_tag @user.profile_image.to_s, size: "100x100" %>
  <% else %>
    <%= image_tag "default_img.jpg", size: "100x100" %>
  <% end %>
  
  <div class="col-sm-8">
    <div class="m-3">
    <h3><%= @user.name %></h3>
    <% if @user == current_user %>
      <%= link_to 'edit profile', edit_user_path, class: 'btn btn-outline-primary btn-sm' %>
    <% else %>
      <h3><%= render 'relationships/follow_button', user: @user %></h3>
    <% end %>
    </div>
    <ul class="nav nav-pills">
      
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followings_user_path(@user)) %>">Following  
        <span class="badge badge-secondary"><%= @count_followings %></span></a>
      </li>
      
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower  
        <span class="badge badge-secondary"><%= @count_followers %></span></a>
      </li>
    </ul>

    <div>
      <ul class="nav nav-tabs nav-justified mb-3">
        
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(user_path(@user)) %>">Post 
          <span class="badge badge-secondary"><%= @count_posts %></span></a>
        </li>
      
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes 
          <span class="badge badge-secondary"><%= @count_favposts %></span></a>
        </li>
      </ul>
    
    </div>
    <%= render 'users', users: @followings %>
  </div>
  
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="row">
  <% if @user.profile_image? %>
    <%= image_tag @user.profile_image.to_s, size: "100x100" %>
  <% else %>
    <%= image_tag "default_img.jpg", size: "100x100" %>
  <% end %>
  
  <div class="col-sm-8">
    <div class="m-3">
    <h3><%= @user.name %></h3>
    <% if @user == current_user %>
      <%= link_to 'edit profile', edit_user_path, class: 'btn btn-outline-primary btn-sm' %>
    <% else %>
      <h3><%= render 'relationships/follow_button', user: @user %></h3>
    <% end %>
    </div>
    <ul class="nav nav-pills">
      
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followings_user_path(@user)) %>">Following  
        <span class="badge badge-secondary"><%= @count_followings %></span></a>
      </li>
      
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower  
        <span class="badge badge-secondary"><%= @count_followers %></span></a>
      </li>
    </ul>

    <div>
      <ul class="nav nav-tabs nav-justified mb-3">
        
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(user_path(@user)) %>">Post 
          <span class="badge badge-secondary"><%= @count_posts %></span></a>
        </li>
      
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes 
          <span class="badge badge-secondary"><%= @count_favposts %></span></a>
        </li>
      </ul>
    
    <%= render 'posts/posts', posts: @favposts %>
    
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local:true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <% if @user.profile_image? %>
        <%= image_tag @user.profile_image.url %>
      <% else %>
        <%= image_tag "default_img.jpg", size: "100x100" %>
      <% end %>
      <%= f.label :profile_image, 'Profile Image' %>
      <br>
      <%= f.file_field :profile_image %>
    </div>
    
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <% if @user.profile_image? %>
  <%= image_tag @user.profile_image.to_s, size: "100x100" %>
  <% else %>
  <%= image_tag "default_img.jpg", size: "100x100" %>
  <% end %>
  
  <div class="col-sm-8">
    <div class="m-3">
    <h3><%= @user.name %></h3>
    <% if @user == current_user %>
      <%= link_to 'edit profile', edit_user_path, class: 'btn btn-outline-primary btn-sm' %>
    <% else %>
      <h3><%= render 'relationships/follow_button', user: @user %></h3>
    <% end %>
    </div>
    <ul class="nav nav-pills">
      
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followings_user_path(@user)) %>">Following  
        <span class="badge badge-secondary"><%= @count_followings %></span></a>
      </li>
      
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link 
        <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower  
        <span class="badge badge-secondary"><%= @count_followers %></span></a>
      </li>
    </ul>

    <div>
      <ul class="nav nav-tabs nav-justified mb-3">
        
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(user_path(@user)) %>">Post 
          <span class="badge badge-secondary"><%= @count_posts %></span></a>
        </li>
      
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link
          <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes 
          <span class="badge badge-secondary"><%= @count_favposts %></span></a>
        </li>
      </ul>
    
    </div>
    
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>