config/routes.rb
Rails.application.routes.draw do
 root to: 'toppages#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: "sessions#create"

 delete 'logout', to: 'sessions#destroy'

 get 'signup', to:'users#new'
 
 resources :users, only: [:index, :show, :new, :create, :edit, :update] do
  member do
   get :followings
   get :followers
   get :likes
  end
 end
 
 resources :posts, only: [:new, :show, :create, :destroy] do
   resources :comments, only: [:create]
 end
 
 resources :comments, only: [:destroy]
  
 resources :relationships, only: [:create, :destroy]
 resources :favorites, only: [:create, :destroy]

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController

  def index
    if logged_in?
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
      @users = User.order(id: :desc).page(params[:page]).per(27)
    end
  end
end

app/views/toppages/index.html.erb
<% if logged_in? %>
<div class="row">

  <% @posts.each do |post| %>
  <div class="card">
    <div class="card-top mt-3 ml-3">
      <%= post.user.name %>
    </div>
    <div class="card-body">
      <%= image_tag post.image.to_s, size: "200x200" %>
    </div>
    <div class="card-text mb-3 ml-3">
      <%= link_to 'more...', post_path(post) %>
    </div>
  </div>


<% end %>
  
</div>

<div class="btn-group fixed-bottom m-3" role="group">

  <%= link_to 'POST NOW', new_post_path, class: 'btn btn-outline-primary' %>
  <%= link_to 'VIEW LIKE', likes_user_path(@current_user), class: 'btn btn-outline-primary' %>

</div>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to SharePhoto</h1>
      <%= link_to 'sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>